### ISSUE TITLE
Cannot save file

### ISSUE THREAD

**Issue by leo-hoet** [zachdeibert/docker-images#4]
Hello! I'm new to docker and I don't know if there is something that I'm missing

I downloaded your image and monodevelops works, the only thing is that it doesn't save my projects. When I close it and open again it doesn't have them.

I'm running `sudo docker run -v /tmp:/tmp zachdeibert/monodevelop $DISPLAY $USER`
This code opens monodevelop but also shows `chown: cannot access '/home/leo/*': No such file or directory`

Any help?

**Comment by zachdeibert** [comment]
The filesystem is completely different inside the container than outside the container.  This is why it seems not to save your projects (new container means entirely new filesystem).  To change this, you can use the `-v` option (like you already have with `/tmp` since the files needed to connect to the desktop manager are in `/tmp`).  So for example, if you want `/home/leo/projects` to save to your local machine instead of in the container, you'd run `sudo docker run -v /tmp:/tmp -v /home/leo/projects:/home/leo/projects zachdeibert/monodevelop $DISPLAY $USER`.  Let me know if that fixes your problem.

**Comment by leo-hoet** [comment]
Yes! It works perfectly. Now I can modify my files

Thanks a lot!
